export const dummyProducts = [
  {
    id: 1,
    title: "Premium Wireless Headphones",
    category: "Audio",
    currentPrice: "50000",
    originalPrice: "60000",
    rating: 4.5,
    discount: 20,
    images: [
      "/dummyProduct.avif",
      "/logo.png",
      "/dummyProduct.avif",
    ],
    description:
      "Experience crystal-clear sound with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and comfortable over-ear design for all-day listening comfort.",
    features: [
      "Active noise cancellation",
      "30-hour battery life",
      "Bluetooth 5.2 connectivity",
      "Comfortable memory foam ear cushions",
      "Quick charge - 5 minutes for 4 hours of playback",
      "Built-in microphone for calls",
    ],
    specifications: [
      { label: "Battery Life", value: "30 hours" },
      { label: "Brand", value: "AudioMax" },
      { label: "Connectivity", value: "Bluetooth 5.2, 3.5mm jack" },
      { label: "Model", value: "WH-1000XM5" },
      { label: "Warranty", value: "2 years" },
      { label: "Weight", value: "250g" },
    ],
  },
  {
    id: 2,
    title: "Stylish Watch",
    category: "Accessories",
    currentPrice: "150",
    originalPrice: "200",
    rating: 4.2,
    discount: 20,
    images: ["/dummyProduct.avif"], // single image as array
    description:
      "A sleek and modern watch with premium materials and accurate timekeeping. Perfect for any occasion.",
    features: [
      "Water-resistant up to 50 meters",
      "Leather strap with clasp closure",
      "Stainless steel case",
      "Chronograph functionality",
    ],
    specifications: [
      { label: "Brand", value: "TimeX" },
      { label: "Case Diameter", value: "42mm" },
      { label: "Weight", value: "80g" },
      { label: "Warranty", value: "1 year" },
    ],
  },
  {
    id: 3,
    title: "Smartphone X",
    category: "Electronics",
    currentPrice: "900",
    originalPrice: "1000",
    rating: 4.8,
    discount: 10,
    images: ["/dummyProduct.avif"],
    description:
      "Smartphone X combines high-end performance, stunning display, and long-lasting battery life in one sleek package.",
    features: [
      "6.5-inch OLED display",
      "Triple-lens camera system",
      "Face ID unlock",
      "Fast charging support",
      "128GB storage",
    ],
    specifications: [
      { label: "Battery", value: "4000mAh" },
      { label: "RAM", value: "8GB" },
      { label: "Storage", value: "128GB" },
      { label: "OS", value: "iOS 17" },
      { label: "Weight", value: "180g" },
    ],
  },
  {
    id: 4,
    title: "Apple Watch (1st Copy)",
    category: "Electronics",
    currentPrice: "799.99",
    originalPrice: "899.99",
    rating: 4.6,
    discount: 11,
    images: ["/dummyProduct.avif"],
    description:
      "Smartphone Y delivers premium performance with excellent camera and battery life at a great price.",
    features: [
      "6.1-inch AMOLED display",
      "Dual-lens camera system",
      "Fast charging",
      "128GB storage",
    ],
    specifications: [
      { label: "Battery", value: "3500mAh" },
      { label: "RAM", value: "6GB" },
      { label: "Storage", value: "128GB" },
      { label: "OS", value: "Android 14" },
      { label: "Weight", value: "170g" },
    ],
  },
  {
    id: 5,
    title: "Wireless Earbuds Z",
    category: "Audio",
    currentPrice: "129.99",
    originalPrice: "159.99",
    rating: 4.4,
    discount: 18,
    images: ["/dummyProduct.avif"],
    description:
      "Compact wireless earbuds with excellent sound quality, long battery life, and ergonomic design for comfortable all-day use.",
    features: [
      "Noise isolation",
      "20-hour total battery life",
      "Touch controls",
      "Water-resistant IPX5",
    ],
    specifications: [
      { label: "Battery", value: "300mAh per earbud" },
      { label: "Brand", value: "AudioMax" },
      { label: "Connectivity", value: "Bluetooth 5.0" },
      { label: "Weight", value: "50g" },
    ],
  },
];
