export const dummyProducts = [
  {
    id: 1,
    title: "Premium Wireless Headphones",
    category: "Audio",
    currentPrice: "199.99",
    originalPrice: "249.99",
    rating: 4.5,
    imageUrl: "/dummyProduct.avif",
    discount: 20,
  },
  {
    id: 2,
    title: "Stylish Watch",
    category: "Accessories",
    currentPrice: "159.99",
    originalPrice: "199.99",
    rating: 4.2,
    imageUrl: "/dummyProduct.avif",
    discount: 20,
  },
  {
    id: 3,
    title: "Smartphone X",
    category: "Electronics",
    currentPrice: "899.99",
    originalPrice: "999.99",
    rating: 4.8,
    imageUrl: "/dummyProduct.avif",
    discount: 10,
  },
  {
    id: 4,
    title: "Smartphone X",
    category: "Electronics",
    currentPrice: "899.99",
    originalPrice: "999.99",
    rating: 4.8,
    imageUrl: "/dummyProduct.avif",
    discount: 10,
  },
  {
    id: 5,
    title: "Smartphone X",
    category: "Electronics",
    currentPrice: "899.99",
    originalPrice: "999.99",
    rating: 4.8,
    imageUrl: "/dummyProduct.avif",
    discount: 10,
  },
];