export const dummyProducts = [
  {
    id: 1,
    title: "Premium Wireless Headphones",
    category: "Audio",
    currentPrice: "200",
    originalPrice: "250",
    rating: 4.5,
    imageUrl: "/dummyProduct.avif",
    discount: 20,
  },
  {
    id: 2,
    title: "Stylish Watch",
    category: "Accessories",
    currentPrice: "150",
    originalPrice: "200",
    rating: 4.2,
    imageUrl: "/dummyProduct.avif",
    discount: 20,
  },
  {
    id: 3,
    title: "Smartphone X",
    category: "Electronics",
    currentPrice: "900",
    originalPrice: "1000",
    rating: 4.8,
    imageUrl: "/dummyProduct.avif",
    discount: 10,
  },
  {
    id: 4,
    title: "Apple Watch (1st Copy)",
    category: "Electronics",
    currentPrice: "900",
    originalPrice: "1000",
    rating: 4.8,
    imageUrl: "/dummyProduct.avif",
    discount: 10,
  },
  {
    id: 5,
    title: "Guci Ladies Bag",
    category: "Electronics",
    currentPrice: "500",
    originalPrice: "5000",
    rating: 4.8,
    imageUrl: "/dummyProduct.avif",
    discount: 10,
  },
];