// lib/errors/domainErrors.ts
export enum DomainErrorCode {
  EMAIL_EXISTS = "EMAIL_EXISTS",
  CREATE_USER_FAILED = "CREATE_USER_FAILED",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  CODE_NOT_FOUND = "CODE_NOT_FOUND",
  CODE_EXPIRED = "CODE_EXPIRED",
  CODE_INVALID = "CODE_INVALID",
  CODE_TOO_MANY_ATTEMPTS = "CODE_TOO_MANY_ATTEMPTS",
  RESEND_TOO_SOON = "RESEND_TOO_SOON",
}
