-- ============================================================
-- Shei Hoise -- Combined migrations
-- Auto-generated by concatenating every file in supabase/migrations/
-- in chronological (filename) order. Do NOT put this file inside
-- supabase/migrations/ -- the Supabase CLI would try to re-apply
-- it as a new migration and every already-applied statement in it
-- would error out as 'already exists'.
-- Generated: 2026-07-15
-- ============================================================


-- ============================================================
-- Source: supabase/migrations/20260105190522_remote_schema.sql
-- ============================================================


-- ============================================================
-- Source: supabase/migrations/20260703120000_facebook_commerce_and_trial_system.sql
-- ============================================================
-- Facebook Commerce Suite (CAPI + risk scoring) + trial/subscription defaults
-- Review before applying to a live database. Safe to run multiple times
-- (IF NOT EXISTS / IF EXISTS guards throughout).

-- ── 1. Conversions API credentials on store_settings ─────────────────────────
ALTER TABLE "public"."store_settings"
  ADD COLUMN IF NOT EXISTS "facebook_capi_access_token" "text",
  ADD COLUMN IF NOT EXISTS "facebook_test_event_code" character varying;

-- ── 2. CAPI delivery tracking on pixel_events ─────────────────────────────────
ALTER TABLE "public"."pixel_events"
  ADD COLUMN IF NOT EXISTS "capi_delivered" boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS "capi_error" "text";

-- ── 3. Close the open pixel_events insert policy ──────────────────────────────
-- All inserts now go exclusively through the service-role API route
-- (/api/pixel-event); no anon/authenticated client should insert directly.
DROP POLICY IF EXISTS "public_insert" ON "public"."pixel_events";

-- ── 4. Default trial plan flag ────────────────────────────────────────────────
-- Exactly one subscription_plans row may have this set — new stores are
-- auto-enrolled into whichever plan has is_default_trial_plan = true.
ALTER TABLE "public"."subscription_plans"
  ADD COLUMN IF NOT EXISTS "is_default_trial_plan" boolean DEFAULT false NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "one_default_trial_plan"
  ON "public"."subscription_plans" ("is_default_trial_plan")
  WHERE "is_default_trial_plan" = true;

-- ── 5. COD fake-order risk scoring ────────────────────────────────────────────
-- Deliberately NOT scoped by store_id — pooling signal across every store
-- on the platform is the point. service_role-only: RLS is enabled with no
-- policies for anon/authenticated, so those roles get zero access by default.
CREATE TABLE IF NOT EXISTS "public"."customer_risk_profiles" (
    "phone_number" "text" PRIMARY KEY,
    "total_orders" integer DEFAULT 0 NOT NULL,
    "delivered_orders" integer DEFAULT 0 NOT NULL,
    "cancelled_orders" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."customer_risk_profiles" OWNER TO "postgres";
ALTER TABLE "public"."customer_risk_profiles" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS "public"."customer_risk_store_touches" (
    "phone_number" "text" NOT NULL,
    "store_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("phone_number", "store_id")
);
ALTER TABLE "public"."customer_risk_store_touches" OWNER TO "postgres";
ALTER TABLE "public"."customer_risk_store_touches" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."customer_risk_store_touches"
    ADD CONSTRAINT "customer_risk_store_touches_store_id_fkey"
    FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Deliberately service_role only — no anon/authenticated grant at all.
GRANT ALL ON TABLE "public"."customer_risk_profiles" TO "service_role";
GRANT ALL ON TABLE "public"."customer_risk_store_touches" TO "service_role";

-- ── 6. Purchase-event send status per order ───────────────────────────────────
-- Tracks whether the Facebook Purchase event for this order was sent
-- immediately, held pending delivery (high risk phone), or suppressed
-- (order was cancelled before ever being sent).
ALTER TABLE "public"."orders"
  ADD COLUMN IF NOT EXISTS "fb_purchase_event_status" character varying(20) DEFAULT 'sent';

DO $$ BEGIN
  ALTER TABLE "public"."orders"
    ADD CONSTRAINT "orders_fb_purchase_event_status_check"
    CHECK (("fb_purchase_event_status")::"text" = ANY (ARRAY[
      ('sent'::character varying)::"text",
      ('held'::character varying)::"text",
      ('suppressed'::character varying)::"text"
    ]));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- Source: supabase/migrations/20260704000000_add_submitted_invoice_status.sql
-- ============================================================
-- Fixes a pre-existing schema/code mismatch: the application (select-plan,
-- submit-payment routes, and the subscription lock screen) has always used
-- "submitted" as the invoice status meaning "payment reference submitted,
-- awaiting admin review" — but the invoice_status enum never actually
-- included that value, causing every plan subscription attempt to fail with
-- "invalid input value for enum invoice_status: submitted".
--
-- ALTER TYPE ... ADD VALUE cannot run inside the same transaction as other
-- statements that use the new value, but is safe on its own — apply this
-- migration by itself.
ALTER TYPE "public"."invoice_status" ADD VALUE IF NOT EXISTS 'submitted' AFTER 'unpaid';


-- ============================================================
-- Source: supabase/migrations/20260706120000_add_pathao_credentials.sql
-- ============================================================
-- Pathao Courier integration — per-store merchant credentials.
-- Safe to run multiple times (IF NOT EXISTS guards throughout).

-- Holds OAuth secrets (client_secret, access_token, refresh_token) as
-- application-level ciphertext (see src/lib/utils/encryption.ts) — never
-- plaintext. Service-role only: RLS is enabled with no policies for
-- anon/authenticated, so those roles get zero access by default, matching
-- the customer_risk_profiles precedent. All reads/writes go through
-- "use server" actions using supabaseAdmin.
CREATE TABLE IF NOT EXISTS "public"."store_pathao_credentials" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "client_id" "text" NOT NULL,
    "client_secret" "text" NOT NULL,
    "access_token" "text",
    "refresh_token" "text",
    "token_expires_at" timestamp with time zone,
    "pathao_store_id" integer,
    "pathao_store_name" character varying(255),
    "connected_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("store_id")
);
ALTER TABLE "public"."store_pathao_credentials" OWNER TO "postgres";
ALTER TABLE "public"."store_pathao_credentials" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."store_pathao_credentials"
    ADD CONSTRAINT "store_pathao_credentials_store_id_fkey"
    FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT ALL ON TABLE "public"."store_pathao_credentials" TO "service_role";


-- ============================================================
-- Source: supabase/migrations/20260706130000_add_pathao_order_fields.sql
-- ============================================================
-- Pathao Courier integration — per-order shipment tracking.
-- Safe to run multiple times (IF NOT EXISTS guards throughout).

ALTER TABLE "public"."orders"
  ADD COLUMN IF NOT EXISTS "pathao_consignment_id" "text",
  ADD COLUMN IF NOT EXISTS "pathao_order_status" character varying(50);


-- ============================================================
-- Source: supabase/migrations/20260706140000_add_pathao_environment.sql
-- ============================================================
-- Pathao Courier integration — track which environment (sandbox/live) each
-- store's connection uses, so API calls can route to the right host.
-- Safe to run multiple times.

ALTER TABLE "public"."store_pathao_credentials"
  ADD COLUMN IF NOT EXISTS "environment" character varying(10) NOT NULL DEFAULT 'sandbox';

DO $$ BEGIN
  ALTER TABLE "public"."store_pathao_credentials"
    ADD CONSTRAINT "store_pathao_credentials_environment_check"
    CHECK (("environment")::"text" = ANY (ARRAY[('sandbox'::character varying)::"text", ('live'::character varying)::"text"]));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- Source: supabase/migrations/20260706150000_pathao_multiple_accounts.sql
-- ============================================================
-- Pathao Courier integration — support connecting multiple Pathao merchant
-- accounts per store, chosen per shipment. Safe to run multiple times.

ALTER TABLE "public"."store_pathao_credentials"
  DROP CONSTRAINT IF EXISTS "store_pathao_credentials_store_id_key";

ALTER TABLE "public"."store_pathao_credentials"
  ADD COLUMN IF NOT EXISTS "label" character varying(100) NOT NULL DEFAULT 'Pathao Account';

ALTER TABLE "public"."orders"
  ADD COLUMN IF NOT EXISTS "pathao_credential_id" "uuid";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pathao_credential_id_fkey"
    FOREIGN KEY ("pathao_credential_id") REFERENCES "public"."store_pathao_credentials"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- Source: supabase/migrations/20260707100000_add_pathao_shipment_details.sql
-- ============================================================
ALTER TABLE "public"."orders"
  ADD COLUMN IF NOT EXISTS "pathao_shipment_details" "jsonb";


-- ============================================================
-- Source: supabase/migrations/20260707120000_add_steadfast_courier.sql
-- ============================================================
-- Widen the existing Pathao credentials table into a generic courier credentials table.
ALTER TABLE "public"."store_pathao_credentials" RENAME TO "store_courier_credentials";

ALTER TABLE "public"."store_courier_credentials"
  ADD COLUMN IF NOT EXISTS "courier" character varying(20) NOT NULL DEFAULT 'pathao',
  ADD COLUMN IF NOT EXISTS "api_key" "text",
  ADD COLUMN IF NOT EXISTS "secret_key" "text";

ALTER TABLE "public"."store_courier_credentials" ALTER COLUMN "client_id" DROP NOT NULL;
ALTER TABLE "public"."store_courier_credentials" ALTER COLUMN "client_secret" DROP NOT NULL;
ALTER TABLE "public"."store_courier_credentials" ALTER COLUMN "courier" DROP DEFAULT;

DO $$ BEGIN
  ALTER TABLE "public"."store_courier_credentials"
    ADD CONSTRAINT "store_courier_credentials_courier_check"
    CHECK (("courier")::"text" = ANY (ARRAY[('pathao'::character varying)::"text", ('steadfast'::character varying)::"text"]));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Generalize the per-order shipment columns so any courier can populate them.
ALTER TABLE "public"."orders" RENAME COLUMN "pathao_credential_id" TO "courier_credential_id";
ALTER TABLE "public"."orders" RENAME COLUMN "pathao_consignment_id" TO "courier_consignment_id";
ALTER TABLE "public"."orders" RENAME COLUMN "pathao_order_status" TO "courier_order_status";
ALTER TABLE "public"."orders" RENAME COLUMN "pathao_shipment_details" TO "courier_shipment_details";
ALTER TABLE "public"."orders" ADD COLUMN IF NOT EXISTS "courier" character varying(20);
UPDATE "public"."orders" SET "courier" = 'pathao' WHERE "courier_consignment_id" IS NOT NULL AND "courier" IS NULL;


-- ============================================================
-- Source: supabase/migrations/20260707130000_add_delivery_couriers.sql
-- ============================================================
ALTER TABLE "public"."store_settings"
  ADD COLUMN IF NOT EXISTS "delivery_couriers" "jsonb" DEFAULT '[]'::jsonb;


-- ============================================================
-- Source: supabase/migrations/20260707140000_seed_builtin_delivery_couriers.sql
-- ============================================================
-- Pathao and Steadfast must come from the same DB-driven list as any custom
-- courier, not be hardcoded in the frontend. Prepend them to every store's
-- delivery_couriers if not already present, preserving any custom couriers
-- already saved there.
UPDATE "public"."store_settings"
SET "delivery_couriers" =
  (CASE
     WHEN COALESCE("delivery_couriers", '[]'::jsonb) @> '[{"id":"pathao"}]'::jsonb
     THEN '[]'::jsonb
     ELSE '[{"id":"pathao","name":"Pathao","type":"pathao","deletable":false,"created_at":"2026-01-01T00:00:00.000Z"}]'::jsonb
   END)
  ||
  (CASE
     WHEN COALESCE("delivery_couriers", '[]'::jsonb) @> '[{"id":"steadfast"}]'::jsonb
     THEN '[]'::jsonb
     ELSE '[{"id":"steadfast","name":"Steadfast","type":"steadfast","deletable":false,"created_at":"2026-01-01T00:00:00.000Z"}]'::jsonb
   END)
  || COALESCE("delivery_couriers", '[]'::jsonb);

-- New stores (and any store_settings row inserted without specifying this
-- column) get the same two built-ins by default from now on.
ALTER TABLE "public"."store_settings"
  ALTER COLUMN "delivery_couriers" SET DEFAULT
  '[{"id":"pathao","name":"Pathao","type":"pathao","deletable":false,"created_at":"2026-01-01T00:00:00.000Z"},
    {"id":"steadfast","name":"Steadfast","type":"steadfast","deletable":false,"created_at":"2026-01-01T00:00:00.000Z"}]'::jsonb;


-- ============================================================
-- Source: supabase/migrations/20260707150000_add_courier_shipment_history.sql
-- ============================================================
-- Switching an order's Delivery Courier must never silently destroy the
-- previous courier's shipment record (tracking id, status, cost details) —
-- production data, needed for disputes/reconciliation across many stores.
-- Every time the active shipment fields get cleared for a courier switch,
-- they're archived here first instead of being lost.
ALTER TABLE "public"."orders"
  ADD COLUMN IF NOT EXISTS "courier_shipment_history" "jsonb" DEFAULT '[]'::jsonb;


-- ============================================================
-- Source: supabase/migrations/20260707160000_add_courier_tracking_table.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."courier_tracking" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "order_id" "uuid" NOT NULL,
    "store_id" "uuid" NOT NULL,
    "courier" character varying(20) NOT NULL,
    "courier_credential_id" "uuid",
    "consignment_id" "text" NOT NULL,
    "status" character varying(100),
    "shipment_details" "jsonb",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id")
);
ALTER TABLE "public"."courier_tracking" OWNER TO "postgres";
ALTER TABLE "public"."courier_tracking" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."courier_tracking"
    ADD CONSTRAINT "courier_tracking_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."courier_tracking"
    ADD CONSTRAINT "courier_tracking_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."courier_tracking"
    ADD CONSTRAINT "courier_tracking_credential_id_fkey" FOREIGN KEY ("courier_credential_id") REFERENCES "public"."store_courier_credentials"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Postgres enforces "at most one active shipment per order" instead of application code.
CREATE UNIQUE INDEX IF NOT EXISTS "courier_tracking_one_active_per_order" ON "public"."courier_tracking" ("order_id") WHERE ("is_active");
CREATE INDEX IF NOT EXISTS "courier_tracking_order_id_idx" ON "public"."courier_tracking" ("order_id");
CREATE INDEX IF NOT EXISTS "courier_tracking_store_courier_idx" ON "public"."courier_tracking" ("store_id", "courier");

GRANT ALL ON TABLE "public"."courier_tracking" TO "service_role";
-- No anon/authenticated policies — same pattern as store_courier_credentials; all access goes through supabaseAdmin.

-- Backfill: every order currently carrying an active shipment becomes one row.
INSERT INTO "public"."courier_tracking" ("order_id", "store_id", "courier", "courier_credential_id", "consignment_id", "status", "shipment_details", "is_active", "created_at", "updated_at")
SELECT "id", "store_id", "courier", "courier_credential_id", "courier_consignment_id", "courier_order_status", "courier_shipment_details", true, "created_at", "updated_at"
FROM "public"."orders"
WHERE "courier_consignment_id" IS NOT NULL
ON CONFLICT DO NOTHING;

-- Backfill: every entry already archived in courier_shipment_history (from the prior
-- migration's approach) becomes an inactive row — only runs if that column actually
-- exists (its own migration may never have been applied, in which case there's
-- nothing to migrate). PL/pgSQL only prepares this statement if the IF is true, so
-- it's safe to reference the column here even when it doesn't exist.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'courier_shipment_history'
  ) THEN
    INSERT INTO "public"."courier_tracking" ("order_id", "store_id", "courier", "courier_credential_id", "consignment_id", "status", "shipment_details", "is_active", "created_at", "updated_at")
    SELECT "o"."id", "o"."store_id",
           ("h"->>'courier')::character varying,
           NULLIF("h"->>'credentialId', '')::uuid,
           "h"->>'consignmentId',
           "h"->>'orderStatus',
           "h"->'shipmentDetails',
           false,
           COALESCE(("h"->>'archivedAt')::timestamp with time zone, now()),
           COALESCE(("h"->>'archivedAt')::timestamp with time zone, now())
    FROM "public"."orders" "o", LATERAL jsonb_array_elements(COALESCE("o"."courier_shipment_history", '[]'::jsonb)) "h"
    WHERE "o"."courier_shipment_history" IS NOT NULL AND jsonb_array_length("o"."courier_shipment_history") > 0;
  END IF;
END $$;

-- Now that everything is preserved as real rows, drop the columns being replaced.
ALTER TABLE "public"."orders"
  DROP COLUMN IF EXISTS "courier_consignment_id",
  DROP COLUMN IF EXISTS "courier_order_status",
  DROP COLUMN IF EXISTS "courier_credential_id",
  DROP COLUMN IF EXISTS "courier_shipment_details",
  DROP COLUMN IF EXISTS "courier_shipment_history";


-- ============================================================
-- Source: supabase/migrations/20260708100000_add_pathao_webhook_secret.sql
-- ============================================================
-- Per-connection webhook secret (encrypted, same as client_secret/api_key) — each
-- store registers its own callback URL in its own Pathao merchant panel, so each
-- connected account needs its own secret rather than one shared across stores.
ALTER TABLE "public"."store_courier_credentials" ADD COLUMN IF NOT EXISTS "webhook_secret" "text";

-- Temporary capture table for raw Pathao webhook payloads. Pathao's docs only show
-- the verification handshake body — this lets us see the real shape of an actual
-- event (Delivered, Payment Invoice, etc.) once one is triggered, instead of
-- guessing field names before building the real parser.
CREATE TABLE IF NOT EXISTS "public"."pathao_webhook_debug_log" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "credential_id" "uuid",
    "headers" "jsonb",
    "body" "jsonb",
    "received_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id")
);
ALTER TABLE "public"."pathao_webhook_debug_log" OWNER TO "postgres";
ALTER TABLE "public"."pathao_webhook_debug_log" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."pathao_webhook_debug_log" TO "service_role";
-- No anon/authenticated policies — same pattern as courier_tracking; all access
-- goes through supabaseAdmin. Not FK-constrained to store_courier_credentials
-- since the incoming credential_id comes from an unauthenticated public URL and
-- shouldn't ever fail the insert just because it's malformed or stale.


-- ============================================================
-- Source: supabase/migrations/20260709000000_add_stock_movements_and_atomic_inventory.sql
-- ============================================================
-- Stock movements: append-only audit trail for every inventory change (manual
-- adjustment, recount, or bulk update), plus atomic RPCs so concurrent writes
-- can never silently clobber each other the way a plain client-side
-- read-current -> compute-new -> overwrite UPDATE can.

CREATE TABLE IF NOT EXISTS "public"."stock_movements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "product_id" "uuid" NOT NULL,
    "variant_id" "uuid",
    "delta" integer NOT NULL,
    "previous_quantity" integer NOT NULL,
    "new_quantity" integer NOT NULL,
    "reason" character varying(50) DEFAULT 'manual_adjustment' NOT NULL,
    "note" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id")
);
ALTER TABLE "public"."stock_movements" OWNER TO "postgres";
ALTER TABLE "public"."stock_movements" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."stock_movements"
    ADD CONSTRAINT "stock_movements_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."stock_movements"
    ADD CONSTRAINT "stock_movements_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."stock_movements"
    ADD CONSTRAINT "stock_movements_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "stock_movements_product_id_idx" ON "public"."stock_movements" ("product_id");
CREATE INDEX IF NOT EXISTS "stock_movements_variant_id_idx" ON "public"."stock_movements" ("variant_id");
CREATE INDEX IF NOT EXISTS "stock_movements_created_at_idx" ON "public"."stock_movements" ("created_at" DESC);

GRANT ALL ON TABLE "public"."stock_movements" TO "service_role";
-- No anon/authenticated policies — all access goes through supabaseAdmin, same pattern as courier_tracking.

-- ── Atomic relative adjustment ──────────────────────────────────────────────
-- Applies quantity_available = quantity_available + p_delta under a row lock
-- (SELECT ... FOR UPDATE), so two concurrent adjustments — or an admin edit
-- racing an order-driven change — always sum correctly instead of one
-- overwrite silently discarding the other. Every call is logged.
CREATE OR REPLACE FUNCTION "public"."adjust_inventory"(
    "p_product_id" "uuid",
    "p_variant_id" "uuid",
    "p_delta" integer,
    "p_reason" character varying DEFAULT 'manual_adjustment',
    "p_note" "text" DEFAULT NULL,
    "p_created_by" "uuid" DEFAULT NULL
) RETURNS TABLE("previous_quantity" integer, "new_quantity" integer)
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_prev integer;
  v_new integer;
BEGIN
  SELECT quantity_available INTO v_prev
  FROM public.product_inventory
  WHERE product_id = p_product_id
    AND variant_id IS NOT DISTINCT FROM p_variant_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No inventory row for product % / variant %', p_product_id, p_variant_id;
  END IF;

  v_new := v_prev + p_delta;

  IF v_new < 0 THEN
    RAISE EXCEPTION 'Insufficient stock: have %, requested change %', v_prev, p_delta;
  END IF;

  UPDATE public.product_inventory
  SET quantity_available = v_new, updated_at = now()
  WHERE product_id = p_product_id
    AND variant_id IS NOT DISTINCT FROM p_variant_id;

  INSERT INTO public.stock_movements
    (product_id, variant_id, delta, previous_quantity, new_quantity, reason, note, created_by)
  VALUES
    (p_product_id, p_variant_id, p_delta, v_prev, v_new, COALESCE(p_reason, 'manual_adjustment'), p_note, p_created_by);

  RETURN QUERY SELECT v_prev, v_new;
END;
$$;
ALTER FUNCTION "public"."adjust_inventory"("uuid", "uuid", integer, character varying, "text", "uuid") OWNER TO "postgres";
GRANT ALL ON FUNCTION "public"."adjust_inventory"("uuid", "uuid", integer, character varying, "text", "uuid") TO "service_role";

-- ── Atomic absolute set ─────────────────────────────────────────────────────
-- For deliberate full recounts/stocktakes where the target number is known
-- and should win outright. Still row-locked and logged — the difference vs.
-- adjust_inventory is purely in what's authoritative (the target vs. a delta).
CREATE OR REPLACE FUNCTION "public"."set_inventory"(
    "p_product_id" "uuid",
    "p_variant_id" "uuid",
    "p_quantity" integer,
    "p_reason" character varying DEFAULT 'recount',
    "p_note" "text" DEFAULT NULL,
    "p_created_by" "uuid" DEFAULT NULL
) RETURNS TABLE("previous_quantity" integer, "new_quantity" integer)
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_prev integer;
BEGIN
  IF p_quantity < 0 THEN
    RAISE EXCEPTION 'Quantity cannot be negative';
  END IF;

  SELECT quantity_available INTO v_prev
  FROM public.product_inventory
  WHERE product_id = p_product_id
    AND variant_id IS NOT DISTINCT FROM p_variant_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No inventory row for product % / variant %', p_product_id, p_variant_id;
  END IF;

  UPDATE public.product_inventory
  SET quantity_available = p_quantity, updated_at = now()
  WHERE product_id = p_product_id
    AND variant_id IS NOT DISTINCT FROM p_variant_id;

  INSERT INTO public.stock_movements
    (product_id, variant_id, delta, previous_quantity, new_quantity, reason, note, created_by)
  VALUES
    (p_product_id, p_variant_id, p_quantity - v_prev, v_prev, p_quantity, COALESCE(p_reason, 'recount'), p_note, p_created_by);

  RETURN QUERY SELECT v_prev, p_quantity;
END;
$$;
ALTER FUNCTION "public"."set_inventory"("uuid", "uuid", integer, character varying, "text", "uuid") OWNER TO "postgres";
GRANT ALL ON FUNCTION "public"."set_inventory"("uuid", "uuid", integer, character varying, "text", "uuid") TO "service_role";


-- ============================================================
-- Source: supabase/migrations/20260711000000_add_vendor_distribution_module.sql
-- ============================================================
-- Vendor Distribution & Vendor Order module.
--
-- Warehouse stock is the existing public.product_inventory table -- there is
-- no separate "warehouse" table in this app, so "warehouse stock" in the
-- feature spec maps directly to product_inventory.quantity_available.
--
-- Vendor stock is tracked as its own pool per (vendor, product, variant) in
-- vendor_stock. Confirming a vendor order moves quantity out of
-- product_inventory and into vendor_stock -- a stock transfer, not a sale.
-- Settlements later move quantity out of vendor_stock: some as "sold"
-- (recorded as receivable), some as "returned" (moved back into
-- product_inventory). All movements are logged to vendor_stock_movements,
-- mirroring the stock_movements/adjust_inventory pattern already used for
-- product_inventory.
--
-- Tenant isolation follows the rest of this app: a store_id column on every
-- table, filtered explicitly in application queries -- no RLS policies here,
-- consistent with products/orders/product_inventory.
--
-- Every "ADD CONSTRAINT" is wrapped in a DO block that swallows both
-- duplicate_object (42710, generic constraint-name conflicts) and
-- duplicate_table (42P07, raised when a UNIQUE/PRIMARY KEY constraint's
-- implicit backing index name conflicts) so this file is safe to re-run in
-- full after a partial failure.

-- -- vendors ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."vendors" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "name" character varying(255) NOT NULL,
    "phone" character varying(30) NOT NULL,
    "address" "text",
    "business_name" character varying(255),
    "notes" "text",
    "status" character varying(20) DEFAULT 'active' NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendors_status_check" CHECK ((("status")::"text" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);
ALTER TABLE "public"."vendors" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendors"
    ADD CONSTRAINT "vendors_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendors_store_id_idx" ON "public"."vendors" ("store_id");

GRANT ALL ON TABLE "public"."vendors" TO "service_role";
GRANT ALL ON TABLE "public"."vendors" TO "authenticated";
GRANT ALL ON TABLE "public"."vendors" TO "anon";

-- -- vendor_stock: current pool held by each vendor ---------------------
CREATE TABLE IF NOT EXISTS "public"."vendor_stock" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "vendor_id" "uuid" NOT NULL,
    "product_id" "uuid" NOT NULL,
    "variant_id" "uuid",
    "quantity_available" integer DEFAULT 0 NOT NULL,
    "last_vendor_tp" numeric(10,2),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendor_stock_quantity_available_check" CHECK ("quantity_available" >= 0)
);
ALTER TABLE "public"."vendor_stock" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock"
    ADD CONSTRAINT "vendor_stock_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock"
    ADD CONSTRAINT "vendor_stock_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock"
    ADD CONSTRAINT "vendor_stock_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock"
    ADD CONSTRAINT "vendor_stock_vendor_id_product_id_variant_id_key" UNIQUE ("vendor_id", "product_id", "variant_id");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_stock_store_id_idx" ON "public"."vendor_stock" ("store_id");
CREATE INDEX IF NOT EXISTS "vendor_stock_vendor_id_idx" ON "public"."vendor_stock" ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_stock_product_id_idx" ON "public"."vendor_stock" ("product_id");

GRANT ALL ON TABLE "public"."vendor_stock" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_stock" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_stock" TO "anon";

-- -- vendor_orders: dispatch / invoice header ----------------------------
CREATE TABLE IF NOT EXISTS "public"."vendor_orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "vendor_id" "uuid" NOT NULL,
    "invoice_number" character varying(50) NOT NULL,
    "status" character varying(20) DEFAULT 'draft' NOT NULL,
    "order_date" "date" NOT NULL,
    "invoice_date" "date",
    "delivery_date" "date",
    "delivery_person" character varying(255),
    "vehicle_number" character varying(100),
    "reference_number" character varying(100),
    "notes" "text",
    "total_quantity" integer DEFAULT 0 NOT NULL,
    "subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "discount_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "grand_total" numeric(12,2) DEFAULT 0 NOT NULL,
    "paid_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "due_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "confirmed_at" timestamp with time zone,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendor_orders_status_check" CHECK ((("status")::"text" = ANY (ARRAY['draft'::"text", 'confirmed'::"text", 'cancelled'::"text"])))
);
ALTER TABLE "public"."vendor_orders" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_orders"
    ADD CONSTRAINT "vendor_orders_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_orders"
    ADD CONSTRAINT "vendor_orders_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_orders"
    ADD CONSTRAINT "vendor_orders_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_orders"
    ADD CONSTRAINT "vendor_orders_store_id_invoice_number_key" UNIQUE ("store_id", "invoice_number");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_orders_store_id_idx" ON "public"."vendor_orders" ("store_id");
CREATE INDEX IF NOT EXISTS "vendor_orders_vendor_id_idx" ON "public"."vendor_orders" ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_orders_status_idx" ON "public"."vendor_orders" ("status");
CREATE INDEX IF NOT EXISTS "vendor_orders_order_date_idx" ON "public"."vendor_orders" ("order_date" DESC);

GRANT ALL ON TABLE "public"."vendor_orders" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_orders" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_orders" TO "anon";

-- -- vendor_order_items: line items (price snapshot at dispatch time) ---
CREATE TABLE IF NOT EXISTS "public"."vendor_order_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "vendor_order_id" "uuid" NOT NULL,
    "product_id" "uuid" NOT NULL,
    "variant_id" "uuid",
    "product_name" character varying(255) NOT NULL,
    "sku" character varying(100),
    "quantity" integer NOT NULL,
    "original_tp" numeric(10,2) NOT NULL,
    "increase_percent" numeric(6,2) DEFAULT 0 NOT NULL,
    "vendor_tp" numeric(10,2) NOT NULL,
    "mrp" numeric(10,2),
    "line_total" numeric(12,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendor_order_items_quantity_check" CHECK ("quantity" > 0)
);
ALTER TABLE "public"."vendor_order_items" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_order_items"
    ADD CONSTRAINT "vendor_order_items_vendor_order_id_fkey" FOREIGN KEY ("vendor_order_id") REFERENCES "public"."vendor_orders"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_order_items"
    ADD CONSTRAINT "vendor_order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_order_items"
    ADD CONSTRAINT "vendor_order_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_order_items_vendor_order_id_idx" ON "public"."vendor_order_items" ("vendor_order_id");
CREATE INDEX IF NOT EXISTS "vendor_order_items_product_id_idx" ON "public"."vendor_order_items" ("product_id");

GRANT ALL ON TABLE "public"."vendor_order_items" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_order_items" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_order_items" TO "anon";

-- -- vendor_settlements: one row per owner visit / settlement event -----
CREATE TABLE IF NOT EXISTS "public"."vendor_settlements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "vendor_id" "uuid" NOT NULL,
    "settlement_date" "date" NOT NULL,
    "notes" "text",
    "total_receivable" numeric(12,2) DEFAULT 0 NOT NULL,
    "total_payment" numeric(12,2) DEFAULT 0 NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id")
);
ALTER TABLE "public"."vendor_settlements" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_settlements"
    ADD CONSTRAINT "vendor_settlements_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_settlements"
    ADD CONSTRAINT "vendor_settlements_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_settlements"
    ADD CONSTRAINT "vendor_settlements_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_settlements_vendor_id_idx" ON "public"."vendor_settlements" ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_settlements_settlement_date_idx" ON "public"."vendor_settlements" ("settlement_date" DESC);

GRANT ALL ON TABLE "public"."vendor_settlements" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_settlements" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_settlements" TO "anon";

-- -- vendor_settlement_items: per-product sold/returned in a settlement -
CREATE TABLE IF NOT EXISTS "public"."vendor_settlement_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "settlement_id" "uuid" NOT NULL,
    "product_id" "uuid" NOT NULL,
    "variant_id" "uuid",
    "sold_quantity" integer DEFAULT 0 NOT NULL,
    "returned_quantity" integer DEFAULT 0 NOT NULL,
    "unit_price" numeric(10,2) NOT NULL,
    "receivable_amount" numeric(12,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendor_settlement_items_sold_quantity_check" CHECK ("sold_quantity" >= 0),
    CONSTRAINT "vendor_settlement_items_returned_quantity_check" CHECK ("returned_quantity" >= 0)
);
ALTER TABLE "public"."vendor_settlement_items" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_settlement_items"
    ADD CONSTRAINT "vendor_settlement_items_settlement_id_fkey" FOREIGN KEY ("settlement_id") REFERENCES "public"."vendor_settlements"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_settlement_items"
    ADD CONSTRAINT "vendor_settlement_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_settlement_items"
    ADD CONSTRAINT "vendor_settlement_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_settlement_items_settlement_id_idx" ON "public"."vendor_settlement_items" ("settlement_id");
CREATE INDEX IF NOT EXISTS "vendor_settlement_items_product_id_idx" ON "public"."vendor_settlement_items" ("product_id");

GRANT ALL ON TABLE "public"."vendor_settlement_items" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_settlement_items" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_settlement_items" TO "anon";

-- -- vendor_payments: every payment received from a vendor --------------
CREATE TABLE IF NOT EXISTS "public"."vendor_payments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "vendor_id" "uuid" NOT NULL,
    "settlement_id" "uuid",
    "amount" numeric(12,2) NOT NULL,
    "payment_date" "date" NOT NULL,
    "notes" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendor_payments_amount_check" CHECK ("amount" > 0)
);
ALTER TABLE "public"."vendor_payments" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_payments"
    ADD CONSTRAINT "vendor_payments_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_payments"
    ADD CONSTRAINT "vendor_payments_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_payments"
    ADD CONSTRAINT "vendor_payments_settlement_id_fkey" FOREIGN KEY ("settlement_id") REFERENCES "public"."vendor_settlements"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_payments"
    ADD CONSTRAINT "vendor_payments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_payments_vendor_id_idx" ON "public"."vendor_payments" ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_payments_payment_date_idx" ON "public"."vendor_payments" ("payment_date" DESC);

GRANT ALL ON TABLE "public"."vendor_payments" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_payments" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_payments" TO "anon";

-- -- vendor_stock_movements: append-only audit trail for vendor_stock ---
CREATE TABLE IF NOT EXISTS "public"."vendor_stock_movements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "vendor_id" "uuid" NOT NULL,
    "product_id" "uuid" NOT NULL,
    "variant_id" "uuid",
    "delta" integer NOT NULL,
    "previous_quantity" integer NOT NULL,
    "new_quantity" integer NOT NULL,
    "reason" character varying(50) NOT NULL,
    "reference_type" character varying(30),
    "reference_id" "uuid",
    "note" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "vendor_stock_movements_reason_check" CHECK ((("reason")::"text" = ANY (ARRAY['dispatch'::"text", 'sold'::"text", 'returned'::"text", 'manual_adjustment'::"text"])))
);
ALTER TABLE "public"."vendor_stock_movements" OWNER TO "postgres";

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock_movements"
    ADD CONSTRAINT "vendor_stock_movements_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock_movements"
    ADD CONSTRAINT "vendor_stock_movements_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock_movements"
    ADD CONSTRAINT "vendor_stock_movements_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_stock_movements"
    ADD CONSTRAINT "vendor_stock_movements_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "vendor_stock_movements_vendor_id_idx" ON "public"."vendor_stock_movements" ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_stock_movements_product_id_idx" ON "public"."vendor_stock_movements" ("product_id");
CREATE INDEX IF NOT EXISTS "vendor_stock_movements_created_at_idx" ON "public"."vendor_stock_movements" ("created_at" DESC);

GRANT ALL ON TABLE "public"."vendor_stock_movements" TO "service_role";
GRANT ALL ON TABLE "public"."vendor_stock_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."vendor_stock_movements" TO "anon";

-- -- confirm_vendor_order: atomic warehouse -> vendor stock transfer ----
-- Locks every affected product_inventory row (ordered by product_id to
-- avoid deadlocks against concurrent confirmations), verifies each item has
-- enough warehouse stock (blocks the whole order if not -- per business
-- rule, no overdraft), then decrements product_inventory and upserts
-- vendor_stock for every line item in one transaction. Logs both
-- stock_movements (reason='vendor_dispatch') and vendor_stock_movements
-- (reason='dispatch').
CREATE OR REPLACE FUNCTION "public"."confirm_vendor_order"(
    "p_vendor_order_id" "uuid",
    "p_created_by" "uuid" DEFAULT NULL
) RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_order record;
  v_item record;
  v_prev_wh integer;
  v_new_wh integer;
  v_prev_vendor integer;
  v_new_vendor integer;
BEGIN
  SELECT id, store_id, vendor_id, status INTO v_order
  FROM public.vendor_orders
  WHERE id = p_vendor_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Vendor order % not found', p_vendor_order_id;
  END IF;

  IF v_order.status <> 'draft' THEN
    RAISE EXCEPTION 'Vendor order % is not in draft status (current: %)', p_vendor_order_id, v_order.status;
  END IF;

  FOR v_item IN
    SELECT product_id, variant_id, quantity, vendor_tp
    FROM public.vendor_order_items
    WHERE vendor_order_id = p_vendor_order_id
    ORDER BY product_id, variant_id
  LOOP
    SELECT quantity_available INTO v_prev_wh
    FROM public.product_inventory
    WHERE product_id = v_item.product_id
      AND variant_id IS NOT DISTINCT FROM v_item.variant_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'No warehouse inventory row for product % / variant %', v_item.product_id, v_item.variant_id;
    END IF;

    IF v_prev_wh < v_item.quantity THEN
      RAISE EXCEPTION 'Insufficient warehouse stock for product %: have %, need %', v_item.product_id, v_prev_wh, v_item.quantity;
    END IF;

    v_new_wh := v_prev_wh - v_item.quantity;

    UPDATE public.product_inventory
    SET quantity_available = v_new_wh, updated_at = now()
    WHERE product_id = v_item.product_id
      AND variant_id IS NOT DISTINCT FROM v_item.variant_id;

    INSERT INTO public.stock_movements
      (product_id, variant_id, delta, previous_quantity, new_quantity, reason, note, created_by)
    VALUES
      (v_item.product_id, v_item.variant_id, -v_item.quantity, v_prev_wh, v_new_wh, 'vendor_dispatch', 'Vendor order ' || p_vendor_order_id, p_created_by);

    SELECT quantity_available INTO v_prev_vendor
    FROM public.vendor_stock
    WHERE vendor_id = v_order.vendor_id
      AND product_id = v_item.product_id
      AND variant_id IS NOT DISTINCT FROM v_item.variant_id
    FOR UPDATE;

    IF NOT FOUND THEN
      v_prev_vendor := 0;
      INSERT INTO public.vendor_stock
        (store_id, vendor_id, product_id, variant_id, quantity_available, last_vendor_tp)
      VALUES
        (v_order.store_id, v_order.vendor_id, v_item.product_id, v_item.variant_id, v_item.quantity, v_item.vendor_tp);
      v_new_vendor := v_item.quantity;
    ELSE
      v_new_vendor := v_prev_vendor + v_item.quantity;
      UPDATE public.vendor_stock
      SET quantity_available = v_new_vendor, last_vendor_tp = v_item.vendor_tp, updated_at = now()
      WHERE vendor_id = v_order.vendor_id
        AND product_id = v_item.product_id
        AND variant_id IS NOT DISTINCT FROM v_item.variant_id;
    END IF;

    INSERT INTO public.vendor_stock_movements
      (vendor_id, product_id, variant_id, delta, previous_quantity, new_quantity, reason, reference_type, reference_id, created_by)
    VALUES
      (v_order.vendor_id, v_item.product_id, v_item.variant_id, v_item.quantity, v_prev_vendor, v_new_vendor, 'dispatch', 'vendor_order', p_vendor_order_id, p_created_by);
  END LOOP;

  UPDATE public.vendor_orders
  SET status = 'confirmed', confirmed_at = now(), updated_at = now()
  WHERE id = p_vendor_order_id;
END;
$$;
ALTER FUNCTION "public"."confirm_vendor_order"("uuid", "uuid") OWNER TO "postgres";
GRANT ALL ON FUNCTION "public"."confirm_vendor_order"("uuid", "uuid") TO "service_role";

-- -- record_vendor_settlement: sold/returned/payment in one transaction -
-- p_items is a JSON array of {product_id, variant_id, sold_quantity,
-- returned_quantity, unit_price}. unit_price is supplied by the caller
-- (defaults client-side to vendor_stock.last_vendor_tp but the owner may
-- override it per line -- necessary because a vendor's pooled stock can mix
-- goods dispatched at different vendor TPs over time).
CREATE OR REPLACE FUNCTION "public"."record_vendor_settlement"(
    "p_vendor_id" "uuid",
    "p_store_id" "uuid",
    "p_settlement_date" "date",
    "p_items" "jsonb",
    "p_payment_amount" numeric DEFAULT 0,
    "p_notes" "text" DEFAULT NULL,
    "p_created_by" "uuid" DEFAULT NULL
) RETURNS "uuid"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_settlement_id uuid;
  v_payment_id uuid;
  v_item jsonb;
  v_product_id uuid;
  v_variant_id uuid;
  v_sold integer;
  v_returned integer;
  v_unit_price numeric(10,2);
  v_prev_vendor integer;
  v_new_vendor integer;
  v_total_out integer;
  v_receivable numeric(12,2);
  v_total_receivable numeric(12,2) := 0;
  v_prev_wh integer;
  v_new_wh integer;
BEGIN
  IF jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one settlement item is required';
  END IF;

  INSERT INTO public.vendor_settlements
    (store_id, vendor_id, settlement_date, notes, total_receivable, total_payment, created_by)
  VALUES
    (p_store_id, p_vendor_id, p_settlement_date, p_notes, 0, GREATEST(p_payment_amount, 0), p_created_by)
  RETURNING id INTO v_settlement_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id := (v_item->>'product_id')::uuid;
    v_variant_id := NULLIF(v_item->>'variant_id', '')::uuid;
    v_sold := COALESCE((v_item->>'sold_quantity')::integer, 0);
    v_returned := COALESCE((v_item->>'returned_quantity')::integer, 0);
    v_unit_price := (v_item->>'unit_price')::numeric;
    v_total_out := v_sold + v_returned;

    IF v_total_out <= 0 THEN
      CONTINUE;
    END IF;

    SELECT quantity_available INTO v_prev_vendor
    FROM public.vendor_stock
    WHERE vendor_id = p_vendor_id
      AND product_id = v_product_id
      AND variant_id IS NOT DISTINCT FROM v_variant_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'No vendor stock row for vendor % / product % / variant %', p_vendor_id, v_product_id, v_variant_id;
    END IF;

    IF v_prev_vendor < v_total_out THEN
      RAISE EXCEPTION 'Insufficient vendor stock for product %: have %, need %', v_product_id, v_prev_vendor, v_total_out;
    END IF;

    v_new_vendor := v_prev_vendor - v_total_out;

    UPDATE public.vendor_stock
    SET quantity_available = v_new_vendor, updated_at = now()
    WHERE vendor_id = p_vendor_id
      AND product_id = v_product_id
      AND variant_id IS NOT DISTINCT FROM v_variant_id;

    v_receivable := v_sold * v_unit_price;
    v_total_receivable := v_total_receivable + v_receivable;

    INSERT INTO public.vendor_settlement_items
      (settlement_id, product_id, variant_id, sold_quantity, returned_quantity, unit_price, receivable_amount)
    VALUES
      (v_settlement_id, v_product_id, v_variant_id, v_sold, v_returned, v_unit_price, v_receivable);

    IF v_sold > 0 THEN
      INSERT INTO public.vendor_stock_movements
        (vendor_id, product_id, variant_id, delta, previous_quantity, new_quantity, reason, reference_type, reference_id, created_by)
      VALUES
        (p_vendor_id, v_product_id, v_variant_id, -v_sold, v_prev_vendor, v_prev_vendor - v_sold, 'sold', 'vendor_settlement', v_settlement_id, p_created_by);
    END IF;

    IF v_returned > 0 THEN
      INSERT INTO public.vendor_stock_movements
        (vendor_id, product_id, variant_id, delta, previous_quantity, new_quantity, reason, reference_type, reference_id, created_by)
      VALUES
        (p_vendor_id, v_product_id, v_variant_id, -v_returned, v_prev_vendor - v_sold, v_new_vendor, 'returned', 'vendor_settlement', v_settlement_id, p_created_by);

      -- Auto-return: goods physically come back, so warehouse stock rises.
      SELECT quantity_available INTO v_prev_wh
      FROM public.product_inventory
      WHERE product_id = v_product_id
        AND variant_id IS NOT DISTINCT FROM v_variant_id
      FOR UPDATE;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'No warehouse inventory row for product % / variant %', v_product_id, v_variant_id;
      END IF;

      v_new_wh := v_prev_wh + v_returned;

      UPDATE public.product_inventory
      SET quantity_available = v_new_wh, updated_at = now()
      WHERE product_id = v_product_id
        AND variant_id IS NOT DISTINCT FROM v_variant_id;

      INSERT INTO public.stock_movements
        (product_id, variant_id, delta, previous_quantity, new_quantity, reason, note, created_by)
      VALUES
        (v_product_id, v_variant_id, v_returned, v_prev_wh, v_new_wh, 'vendor_return', 'Vendor settlement ' || v_settlement_id, p_created_by);
    END IF;
  END LOOP;

  UPDATE public.vendor_settlements
  SET total_receivable = v_total_receivable
  WHERE id = v_settlement_id;

  IF p_payment_amount > 0 THEN
    INSERT INTO public.vendor_payments
      (store_id, vendor_id, settlement_id, amount, payment_date, notes, created_by)
    VALUES
      (p_store_id, p_vendor_id, v_settlement_id, p_payment_amount, p_settlement_date, p_notes, p_created_by)
    RETURNING id INTO v_payment_id;
  END IF;

  RETURN v_settlement_id;
END;
$$;
ALTER FUNCTION "public"."record_vendor_settlement"("uuid", "uuid", "date", "jsonb", numeric, "text", "uuid") OWNER TO "postgres";
GRANT ALL ON FUNCTION "public"."record_vendor_settlement"("uuid", "uuid", "date", "jsonb", numeric, "text", "uuid") TO "service_role";


-- ============================================================
-- Source: supabase/migrations/20260712000000_add_vendor_tables_rls.sql
-- ============================================================
-- Row Level Security for the Vendor Distribution module.
--
-- The rest of this app (products, orders, product_inventory, expenses...)
-- has no RLS and relies entirely on application-level `.eq("store_id", ...)`
-- filtering, which is bypassable by anyone using the public anon key
-- directly against the Supabase REST API. Since vendor tables carry
-- financial data (dues, payments, receivables) and nothing yet depends on
-- them being unrestricted, they get locked down now while it's cheap.
--
-- Policy shape mirrors the one existing precedent in this schema --
-- "owner_read" on public.pixel_events -- which resolves the caller's store
-- via auth.uid() -> public.users.store_id and matches it against the row's
-- store_id. Tables that don't carry store_id directly (the *_items and
-- *_movements audit/line-item tables) join up to their parent row to reach
-- it instead.
--
-- Only SELECT policies are added. All writes to these tables already go
-- through supabaseAdmin (the service_role client) inside "use server"
-- functions and the confirm_vendor_order / record_vendor_settlement RPCs --
-- service_role bypasses RLS entirely, so those keep working unchanged.
-- With RLS enabled and no INSERT/UPDATE/DELETE policy for anon/authenticated,
-- direct writes from the browser's anon-key client are now denied by
-- default, which is the actual goal here.

ALTER TABLE "public"."vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendor_stock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendor_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendor_order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendor_settlements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendor_settlement_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendor_payments" ENABLE ROW LEVEL SECURITY;
-- vendor_stock_movements already had RLS enabled in the prior migration
-- (mirroring stock_movements), with no policies -- i.e. already fully
-- locked down for anon/authenticated. Add the read policy here too so the
-- audit trail is at least viewable by the owning store.
ALTER TABLE "public"."vendor_stock_movements" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vendors_owner_select" ON "public"."vendors";
CREATE POLICY "vendors_owner_select" ON "public"."vendors" FOR SELECT TO "authenticated" USING (
  "store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
);

DROP POLICY IF EXISTS "vendor_stock_owner_select" ON "public"."vendor_stock";
CREATE POLICY "vendor_stock_owner_select" ON "public"."vendor_stock" FOR SELECT TO "authenticated" USING (
  "store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
);

DROP POLICY IF EXISTS "vendor_orders_owner_select" ON "public"."vendor_orders";
CREATE POLICY "vendor_orders_owner_select" ON "public"."vendor_orders" FOR SELECT TO "authenticated" USING (
  "store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
);

DROP POLICY IF EXISTS "vendor_settlements_owner_select" ON "public"."vendor_settlements";
CREATE POLICY "vendor_settlements_owner_select" ON "public"."vendor_settlements" FOR SELECT TO "authenticated" USING (
  "store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
);

DROP POLICY IF EXISTS "vendor_payments_owner_select" ON "public"."vendor_payments";
CREATE POLICY "vendor_payments_owner_select" ON "public"."vendor_payments" FOR SELECT TO "authenticated" USING (
  "store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
);

DROP POLICY IF EXISTS "vendor_order_items_owner_select" ON "public"."vendor_order_items";
CREATE POLICY "vendor_order_items_owner_select" ON "public"."vendor_order_items" FOR SELECT TO "authenticated" USING (
  "vendor_order_id" IN (
    SELECT "vendor_orders"."id" FROM "public"."vendor_orders"
    WHERE "vendor_orders"."store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
  )
);

DROP POLICY IF EXISTS "vendor_settlement_items_owner_select" ON "public"."vendor_settlement_items";
CREATE POLICY "vendor_settlement_items_owner_select" ON "public"."vendor_settlement_items" FOR SELECT TO "authenticated" USING (
  "settlement_id" IN (
    SELECT "vendor_settlements"."id" FROM "public"."vendor_settlements"
    WHERE "vendor_settlements"."store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
  )
);

DROP POLICY IF EXISTS "vendor_stock_movements_owner_select" ON "public"."vendor_stock_movements";
CREATE POLICY "vendor_stock_movements_owner_select" ON "public"."vendor_stock_movements" FOR SELECT TO "authenticated" USING (
  "vendor_id" IN (
    SELECT "vendors"."id" FROM "public"."vendors"
    WHERE "vendors"."store_id" IN (SELECT "users"."store_id" FROM "public"."users" WHERE "users"."id" = "auth"."uid"())
  )
);


-- ============================================================
-- Source: supabase/migrations/20260713000000_add_vendor_payment_method.sql
-- ============================================================
-- Adds a payment_method column to vendor_payments so the owner can record
-- *how* cash was collected from a vendor (COD, cash-in-hand, bKash/Nagad
-- under "mobile_banking", bank transfer, card) -- not just the amount.
-- Reuses the same value set as the existing public.orders payment_method
-- column (see src/lib/types/enums.ts PaymentMethod) rather than inventing a
-- new one, so the concept stays consistent across the app.
--
-- record_vendor_settlement gets a new trailing p_payment_method parameter.
-- CREATE OR REPLACE FUNCTION cannot change a function's argument list --
-- doing so creates a second, overloaded function instead of replacing the
-- original, which then makes PostgREST's RPC resolution ambiguous. The old
-- 7-argument signature is dropped explicitly first so only the new
-- 8-argument version exists afterward.

ALTER TABLE "public"."vendor_payments"
  ADD COLUMN IF NOT EXISTS "payment_method" character varying(30) DEFAULT 'cash' NOT NULL;

DO $$ BEGIN
  ALTER TABLE ONLY "public"."vendor_payments"
    ADD CONSTRAINT "vendor_payments_payment_method_check"
    CHECK (("payment_method")::"text" = ANY (ARRAY['cod'::"text", 'cash'::"text", 'online'::"text", 'card'::"text", 'bank_transfer'::"text", 'mobile_banking'::"text"]));
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

DROP FUNCTION IF EXISTS "public"."record_vendor_settlement"("uuid", "uuid", "date", "jsonb", numeric, "text", "uuid");

CREATE OR REPLACE FUNCTION "public"."record_vendor_settlement"(
    "p_vendor_id" "uuid",
    "p_store_id" "uuid",
    "p_settlement_date" "date",
    "p_items" "jsonb",
    "p_payment_amount" numeric DEFAULT 0,
    "p_notes" "text" DEFAULT NULL,
    "p_created_by" "uuid" DEFAULT NULL,
    "p_payment_method" character varying DEFAULT 'cash'
) RETURNS "uuid"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_settlement_id uuid;
  v_payment_id uuid;
  v_item jsonb;
  v_product_id uuid;
  v_variant_id uuid;
  v_sold integer;
  v_returned integer;
  v_unit_price numeric(10,2);
  v_prev_vendor integer;
  v_new_vendor integer;
  v_total_out integer;
  v_receivable numeric(12,2);
  v_total_receivable numeric(12,2) := 0;
  v_prev_wh integer;
  v_new_wh integer;
BEGIN
  IF jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one settlement item is required';
  END IF;

  INSERT INTO public.vendor_settlements
    (store_id, vendor_id, settlement_date, notes, total_receivable, total_payment, created_by)
  VALUES
    (p_store_id, p_vendor_id, p_settlement_date, p_notes, 0, GREATEST(p_payment_amount, 0), p_created_by)
  RETURNING id INTO v_settlement_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id := (v_item->>'product_id')::uuid;
    v_variant_id := NULLIF(v_item->>'variant_id', '')::uuid;
    v_sold := COALESCE((v_item->>'sold_quantity')::integer, 0);
    v_returned := COALESCE((v_item->>'returned_quantity')::integer, 0);
    v_unit_price := (v_item->>'unit_price')::numeric;
    v_total_out := v_sold + v_returned;

    IF v_total_out <= 0 THEN
      CONTINUE;
    END IF;

    SELECT quantity_available INTO v_prev_vendor
    FROM public.vendor_stock
    WHERE vendor_id = p_vendor_id
      AND product_id = v_product_id
      AND variant_id IS NOT DISTINCT FROM v_variant_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'No vendor stock row for vendor % / product % / variant %', p_vendor_id, v_product_id, v_variant_id;
    END IF;

    IF v_prev_vendor < v_total_out THEN
      RAISE EXCEPTION 'Insufficient vendor stock for product %: have %, need %', v_product_id, v_prev_vendor, v_total_out;
    END IF;

    v_new_vendor := v_prev_vendor - v_total_out;

    UPDATE public.vendor_stock
    SET quantity_available = v_new_vendor, updated_at = now()
    WHERE vendor_id = p_vendor_id
      AND product_id = v_product_id
      AND variant_id IS NOT DISTINCT FROM v_variant_id;

    v_receivable := v_sold * v_unit_price;
    v_total_receivable := v_total_receivable + v_receivable;

    INSERT INTO public.vendor_settlement_items
      (settlement_id, product_id, variant_id, sold_quantity, returned_quantity, unit_price, receivable_amount)
    VALUES
      (v_settlement_id, v_product_id, v_variant_id, v_sold, v_returned, v_unit_price, v_receivable);

    IF v_sold > 0 THEN
      INSERT INTO public.vendor_stock_movements
        (vendor_id, product_id, variant_id, delta, previous_quantity, new_quantity, reason, reference_type, reference_id, created_by)
      VALUES
        (p_vendor_id, v_product_id, v_variant_id, -v_sold, v_prev_vendor, v_prev_vendor - v_sold, 'sold', 'vendor_settlement', v_settlement_id, p_created_by);
    END IF;

    IF v_returned > 0 THEN
      INSERT INTO public.vendor_stock_movements
        (vendor_id, product_id, variant_id, delta, previous_quantity, new_quantity, reason, reference_type, reference_id, created_by)
      VALUES
        (p_vendor_id, v_product_id, v_variant_id, -v_returned, v_prev_vendor - v_sold, v_new_vendor, 'returned', 'vendor_settlement', v_settlement_id, p_created_by);

      -- Auto-return: goods physically come back, so warehouse stock rises.
      SELECT quantity_available INTO v_prev_wh
      FROM public.product_inventory
      WHERE product_id = v_product_id
        AND variant_id IS NOT DISTINCT FROM v_variant_id
      FOR UPDATE;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'No warehouse inventory row for product % / variant %', v_product_id, v_variant_id;
      END IF;

      v_new_wh := v_prev_wh + v_returned;

      UPDATE public.product_inventory
      SET quantity_available = v_new_wh, updated_at = now()
      WHERE product_id = v_product_id
        AND variant_id IS NOT DISTINCT FROM v_variant_id;

      INSERT INTO public.stock_movements
        (product_id, variant_id, delta, previous_quantity, new_quantity, reason, note, created_by)
      VALUES
        (v_product_id, v_variant_id, v_returned, v_prev_wh, v_new_wh, 'vendor_return', 'Vendor settlement ' || v_settlement_id, p_created_by);
    END IF;
  END LOOP;

  UPDATE public.vendor_settlements
  SET total_receivable = v_total_receivable
  WHERE id = v_settlement_id;

  IF p_payment_amount > 0 THEN
    INSERT INTO public.vendor_payments
      (store_id, vendor_id, settlement_id, amount, payment_date, notes, created_by, payment_method)
    VALUES
      (p_store_id, p_vendor_id, v_settlement_id, p_payment_amount, p_settlement_date, p_notes, p_created_by, COALESCE(p_payment_method, 'cash'))
    RETURNING id INTO v_payment_id;
  END IF;

  RETURN v_settlement_id;
END;
$$;
ALTER FUNCTION "public"."record_vendor_settlement"("uuid", "uuid", "date", "jsonb", numeric, "text", "uuid", character varying) OWNER TO "postgres";
GRANT ALL ON FUNCTION "public"."record_vendor_settlement"("uuid", "uuid", "date", "jsonb", numeric, "text", "uuid", character varying) TO "service_role";


-- ============================================================
-- Source: supabase/migrations/20260714000000_add_vendor_order_delivery_cost.sql
-- ============================================================
-- Adds an optional delivery_cost to vendor_orders. Not every dispatch has a
-- courier/vehicle fee, so it defaults to 0 and only shows up in the invoice
-- summary when the owner actually enters something. It's billed to the
-- vendor: grand_total = subtotal + delivery_cost - discount_amount.

ALTER TABLE "public"."vendor_orders"
  ADD COLUMN IF NOT EXISTS "delivery_cost" numeric(12,2) DEFAULT 0 NOT NULL;


-- ============================================================
-- Source: supabase/migrations/20260715000000_fix_dead_supabase_project_image_urls.sql
-- ============================================================
-- Fixes stored image URLs after a Supabase project migration.
--
-- Context: the project was migrated from the old Supabase project
-- (tzmrxxtrkwehdgzeyhgq.supabase.co, now deleted -- its hostname no longer
-- resolves) to the current one (sqvvtaejcfarmxcdvgrz.supabase.co). Storage
-- objects were copied over under the same bucket/path, but these text
-- columns still had the old hostname baked into the stored URL, so every
-- image referencing it 404s.
--
-- Verified before first running this: swapping just the hostname on a
-- broad sample of stored URLs (product images across multiple products,
-- plus all three stores' logo/banner URLs) resolved with HTTP 200 against
-- the new project, confirming the same bucket/path exists there.
-- categories.image_url, customer_profiles.avatar_url, and
-- user_profiles.avatar_url had zero rows on the old host, so they're not
-- included below -- add an UPDATE block for them the same way if that ever
-- changes.
--
-- Reusable for the next project migration: just change old_host/new_host
-- below and re-run. Safe to copy-paste and run again anytime -- the WHERE
-- clause only ever matches rows still pointing at old_host, so it's a
-- no-op once nothing does.

DO $$
DECLARE
  old_host CONSTANT text := 'https://tzmrxxtrkwehdgzeyhgq.supabase.co';
  new_host CONSTANT text := 'https://sqvvtaejcfarmxcdvgrz.supabase.co';
  updated_count integer;
BEGIN
  UPDATE "public"."product_images"
  SET "image_url" = replace("image_url", old_host, new_host)
  WHERE "image_url" LIKE '%' || old_host || '%';
  GET DIAGNOSTICS updated_count = ROW_COUNT;
  RAISE NOTICE 'product_images.image_url rows updated: %', updated_count;

  UPDATE "public"."stores"
  SET "logo_url" = replace("logo_url", old_host, new_host)
  WHERE "logo_url" LIKE '%' || old_host || '%';
  GET DIAGNOSTICS updated_count = ROW_COUNT;
  RAISE NOTICE 'stores.logo_url rows updated: %', updated_count;

  UPDATE "public"."stores"
  SET "banner_url" = replace("banner_url", old_host, new_host)
  WHERE "banner_url" LIKE '%' || old_host || '%';
  GET DIAGNOSTICS updated_count = ROW_COUNT;
  RAISE NOTICE 'stores.banner_url rows updated: %', updated_count;
END $$;

